import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "../components/sidebar";
import Navbar from "../components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
         <Sidebar/>

        {children}
      </body>
    </html>
  );
}
